# Root orchestration for ai-circus-framework. Each service under services/ and each
# UI has its own Makefile (generated by ai-circus-template) for `make check`/`make run`
# from inside that service's directory — this Makefile only orchestrates across them.

.DEFAULT_GOAL := help

ifneq (,$(wildcard .env))
    include .env
    export
endif

CYAN  := $(shell tput setaf 6 2>/dev/null)
RESET := $(shell tput sgr0 2>/dev/null)

.PHONY: help bootstrap up up-infra generate-console-auth check-public-ready down logs pipeline new-service \
	sync-shared check-all clean ollama-up all reset-all wait-infra wait-services verify

help: ## Show this help message
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS=":.*?## "}; {printf "  $(CYAN)%-18s$(RESET) %s\n", $$1, $$2}'

# ── Bootstrap ─────────────────────────────────────────────────────────────────

bootstrap: ## Create .env from .env.example, console.htpasswd from its .example (if missing), and infra/seaweedfs/s3.json from .env
	@if [ ! -f .env ] && [ -f .env.example ]; then echo "📝 Creating .env from .env.example..."; cp .env.example .env; fi
	@if [ ! -f infra/traefik/console.htpasswd ] && [ -f infra/traefik/console.htpasswd.example ]; then \
		echo "📝 Creating infra/traefik/console.htpasswd from its .example (demo credential — rotate with 'make generate-console-auth' before a public deployment)..."; \
		cp infra/traefik/console.htpasswd.example infra/traefik/console.htpasswd; \
	fi
	@./scripts/generate_seaweedfs_s3_config.sh
	@echo "✓ Edit .env (Logto/LLM/SeaweedFS secrets) before running 'make up'"

# ── Compose lifecycle ─────────────────────────────────────────────────────────

up-infra: ## Start only the platform infra (postgres, logto, qdrant, seaweedfs, traefik)
	@docker compose up -d postgres logto qdrant seaweedfs traefik

up: ## Start the full platform (infra + all backend services + the UI)
	@docker compose up -d --build

down: ## Stop and remove all containers
	@docker compose down

logs: ## Tail logs for all running containers
	@docker compose logs -f --tail=200

pipeline: ## Run the one-shot churn ETL -> training pipeline, then (re)start prediction
	@docker compose up --build etl-tabular
	@docker compose up --build training
	@docker compose up -d --build prediction

ollama-up: ## Start the optional bundled Ollama (free, no-API-key LLM fallback; pulls llama3.2:3b, ~2GB, on first run)
	@docker compose --profile ollama up -d ollama ollama-pull

# ── Public deployment (any public VM, or minikube behind a public Ingress) — no
# separate compose file or `up` variant: `make up` already serves both
# local dev and a real deployment, differentiated purely by .env (same as
# ADMIN_API_KEY/OBJECT_STORE_SECRET_KEY/etc. always have been). See README "Public
# deployment" for the full checklist; the two commands below cover the parts that
# are easy to forget.

generate-console-auth: ## (Re)generate infra/traefik/console.htpasswd — the Basic Auth credential gating admin.logto/console.objectstore — usage: make generate-console-auth [CONSOLE_USER=admin]
	@./scripts/generate_console_auth.sh "$(CONSOLE_USER)"

check-public-ready: ## Verify .env/console.htpasswd don't still hold shipped demo values before a public deployment (does not start/stop anything)
	@ok=1; \
	if [ "$${DEPLOYMENT_TARGET:-local}" != "public" ]; then \
		echo "❌ DEPLOYMENT_TARGET is not 'public' in .env — every service's boot-time guard is a no-op until it is"; ok=0; \
	fi; \
	if [ "$${ADMIN_API_KEY:-ai-circus-2026}" = "ai-circus-2026" ]; then \
		echo "❌ ADMIN_API_KEY is still the shipped demo default — rotate it or blank it in .env"; ok=0; \
	fi; \
	if [ "$${ENGINEERING_DEMO_API_KEY:-}" = "ai-circus-engineering-2026" ]; then \
		echo "❌ ENGINEERING_DEMO_API_KEY is still the shipped demo default — rotate it or blank it in .env"; ok=0; \
	fi; \
	if [ "$${AUTH_DISABLED:-false}" = "true" ]; then \
		echo "❌ AUTH_DISABLED=true in .env — this bypasses Logto entirely, never set it for a public deployment"; ok=0; \
	fi; \
	if [ ! -f infra/traefik/console.htpasswd ]; then \
		echo "❌ infra/traefik/console.htpasswd is missing — run 'make generate-console-auth'"; ok=0; \
	elif [ -f infra/traefik/console.htpasswd.example ] && cmp -s infra/traefik/console.htpasswd infra/traefik/console.htpasswd.example; then \
		echo "❌ infra/traefik/console.htpasswd still holds the shipped demo credential — run 'make generate-console-auth'"; ok=0; \
	fi; \
	if [ -f infra/seaweedfs/s3.json.example ] && cmp -s infra/seaweedfs/s3.json infra/seaweedfs/s3.json.example 2>/dev/null; then \
		echo "❌ infra/seaweedfs/s3.json still holds the shipped demo credential — set OBJECT_STORE_ACCESS_KEY/SECRET_KEY in .env then run './scripts/generate_seaweedfs_s3_config.sh'"; ok=0; \
	fi; \
	if [ "$$ok" = "1" ]; then echo "✓ looks ready for a public deployment — run 'make up' (or 'make all') on the target host"; else exit 1; fi

# ── One-shot setup / troubleshooting ────────────────────────────────────────────
#
# `all` exists because the individual steps above have a real ordering dependency
# (`up` before `pipeline`, both after `up-infra`'s containers are actually healthy —
# not just "started") that's easy to get wrong on a fresh clone, especially on a
# machine other than the one the repo was first set up on. `verify` reproduces the
# exact request the browser's login screen makes, so a "Failed to fetch" in the UI
# can be diagnosed here, with logs, before it's ever a browser mystery.

all: ## One-shot: bootstrap .env, start infra+services, run both pipelines, verify the admin tenant end-to-end (safe to re-run any time; use this instead of the individual up-infra/up/pipeline steps unless you need finer control)
	@$(MAKE) bootstrap
	@$(MAKE) up-infra
	@$(MAKE) wait-infra
	@$(MAKE) up
	@$(MAKE) wait-services
	@$(MAKE) pipeline
	@echo "▶ vectorizing the conversational_rag scenario's reference docs..."
	@docker compose up --build etl-vectorize
	@$(MAKE) verify
	@echo ""
	@echo "🎉 ai-circus-framework is up — open http://aiopen.localhost, pick 'admin' from the User dropdown, and use the ADMIN_API_KEY from .env as the password."
	@if [ -z "$$OPENAI_API_KEY$$GOOGLE_API_KEY$$AZURE_OPENAI_API_KEY$$DEEPSEEK_API_KEY$$GROQ_API_KEY$$OPENROUTER_API_KEY$$ANTHROPIC_API_KEY" ]; then \
		echo "ℹ️  No LLM provider key set in .env — chat (assistant/rag-agent) won't answer yet."; \
		echo "   Add one provider key to .env then 'make up', or run 'make ollama-up' for a free local fallback."; \
	fi

reset-all: ## Nuke containers + volumes + per-service build artifacts, then rebuild fresh via `make all` — the fastest way back to a known-good state, and what to run before sharing this repo so it's proven from a clean slate
	@echo "🧹 tearing down containers + volumes (postgres/logto/qdrant/seaweedfs data all reset)..."
	@docker compose down -v
	@$(MAKE) all

wait-infra: ## Wait for postgres+logto to report healthy (internal step of `make all`; also handy standalone if `make up-infra` seems stuck)
	@echo "⏳ waiting for postgres..."
	@i=0; until [ "$$(docker compose ps postgres --format '{{.Health}}' 2>/dev/null)" = "healthy" ]; do \
		i=$$((i+1)); [ $$i -ge 60 ] && { echo "❌ postgres never became healthy — check: docker compose logs postgres"; exit 1; }; \
		sleep 2; \
	done
	@echo "⏳ waiting for logto (first boot seeds its own DB — can take a couple of minutes)..."
	@i=0; until [ "$$(docker compose ps logto --format '{{.Health}}' 2>/dev/null)" = "healthy" ]; do \
		i=$$((i+1)); [ $$i -ge 90 ] && { echo "❌ logto never became healthy — check: docker compose logs logto"; exit 1; }; \
		sleep 2; \
	done
	@echo "✓ infra healthy"

wait-services: ## Wait for platform-registry and every Traefik-routed backend to answer real requests (internal step of `make all`)
	@echo "⏳ waiting for platform-registry..."
	@i=0; until curl -sf "http://localhost:$${PLATFORM_REGISTRY_PORT:-8010}/healthz" >/dev/null 2>&1; do \
		i=$$((i+1)); [ $$i -ge 60 ] && { echo "❌ platform-registry never came up — check: docker compose logs platform-registry"; exit 1; }; \
		sleep 2; \
	done
	@for host in prediction assistant rag-agent; do \
		echo "⏳ waiting for $$host.localhost (via Traefik)..."; \
		i=0; until curl -sf "http://$$host.localhost/healthz" >/dev/null 2>&1; do \
			i=$$((i+1)); \
			[ $$i -ge 60 ] && { echo "❌ $$host.localhost never answered — check: docker compose logs $$host, and that 'getent hosts $$host.localhost' resolves to 127.0.0.1"; exit 1; }; \
			sleep 2; \
		done; \
	done
	@echo "⏳ waiting for aiopen.localhost..."
	@i=0; until curl -sf "http://aiopen.localhost/" >/dev/null 2>&1; do \
		i=$$((i+1)); [ $$i -ge 60 ] && { echo "❌ aiopen.localhost never answered — check: docker compose logs ui-react, and that port 80 isn't already used by something else on this machine"; exit 1; }; \
		sleep 2; \
	done
	@echo "✓ all services answering"

verify: ## Curl-check the admin (and, if configured, engineering-demo) tenant end-to-end — the exact calls the login screen makes — catches "Failed to fetch"-class setup issues before you open a browser
	@echo "🔎 verifying admin tenant end-to-end..."
	@key="$${ADMIN_API_KEY:-ai-circus-2026}"; \
	code=$$(curl -s -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $$key" "http://localhost:$${PLATFORM_REGISTRY_PORT:-8010}/llm-settings/active-model"); \
	if [ "$$code" = "401" ]; then \
		echo "❌ ADMIN_API_KEY in .env doesn't match what platform-registry is running with — after editing .env, run 'make up' to recreate it"; exit 1; \
	fi; \
	echo "  ✓ admin key accepted by platform-registry ($$code)"
	@key="$${ADMIN_API_KEY:-ai-circus-2026}"; \
	n=$$(curl -s -H "Authorization: Bearer $$key" "http://localhost:$${PLATFORM_REGISTRY_PORT:-8010}/entitlements/admin" | grep -o '"slug"' | wc -l); \
	if [ "$$n" -gt 0 ]; then echo "  ✓ admin tenant is entitled to $$n scenario(s)"; \
	else echo "❌ admin tenant has 0 entitled scenarios — scenario seeding may have failed, check: docker compose logs platform-registry"; exit 1; fi
	@for host in prediction assistant rag-agent; do \
		code=$$(curl -s -o /dev/null -w '%{http_code}' "http://$$host.localhost/healthz"); \
		if [ "$$code" = "200" ]; then echo "  ✓ $$host.localhost reachable ($$code)"; \
		else echo "❌ $$host.localhost -> $$code — this is the exact failure behind a browser 'Failed to fetch'. Check: docker compose ps, docker compose logs $$host, and 'getent hosts $$host.localhost'"; exit 1; fi; \
	done
	@code=$$(curl -s -o /dev/null -w '%{http_code}' "http://aiopen.localhost/"); \
	if [ "$$code" = "200" ]; then echo "  ✓ aiopen.localhost reachable ($$code)"; \
	else echo "❌ aiopen.localhost -> $$code — check: docker compose logs ui-react, and that port 80 isn't already used by something else on this machine"; exit 1; fi
	@echo "✓ admin tenant verified — http://aiopen.localhost is ready for the 'admin' User dropdown login"
	@demo_key="$${ENGINEERING_DEMO_API_KEY:-}"; \
	if [ -z "$$demo_key" ]; then \
		echo "ℹ️  ENGINEERING_DEMO_API_KEY not set in .env — skipping engineering-demo tenant checks"; \
		exit 0; \
	fi; \
	echo "🔎 verifying engineering-demo tenant is scoped correctly..."; \
	code=$$(curl -s -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $$demo_key" "http://localhost:$${PLATFORM_REGISTRY_PORT:-8010}/auth/verify-engineering-demo-key"); \
	if [ "$$code" != "200" ]; then \
		echo "❌ ENGINEERING_DEMO_API_KEY in .env doesn't match what platform-registry is running with ($$code) — after editing .env, run 'make up' to recreate it"; exit 1; \
	fi; \
	echo "  ✓ engineering demo key accepted by platform-registry ($$code)"; \
	slugs=$$(curl -s -H "Authorization: Bearer $$demo_key" "http://localhost:$${PLATFORM_REGISTRY_PORT:-8010}/entitlements/engineering-demo" | grep -o '"slug":"[a-z_]*"' | sort); \
	expected=$$(printf '"slug":"electric_motor"\n"slug":"energy_building"\n"slug":"mpm"'); \
	if [ "$$slugs" = "$$expected" ]; then \
		echo "  ✓ engineering-demo tenant is entitled to exactly mpm/electric_motor/energy_building"; \
	else \
		echo "❌ engineering-demo tenant entitlements don't match — expected mpm/electric_motor/energy_building, got:"; echo "$$slugs"; exit 1; \
	fi; \
	code=$$(curl -s -o /dev/null -w '%{http_code}' -X POST -H "Authorization: Bearer $$demo_key" -H "Content-Type: application/json" -d '{"records":[]}' "http://prediction.localhost/predict/churn"); \
	if [ "$$code" = "403" ]; then \
		echo "  ✓ engineering-demo key correctly denied access to an out-of-scope scenario (churn -> 403)"; \
	else \
		echo "❌ engineering-demo key was NOT denied access to churn (got $$code, expected 403) — scoping enforcement is broken"; exit 1; \
	fi; \
	echo "✓ engineering-demo tenant verified — scoped to exactly mpm/electric_motor/energy_building"

# ── Scaffolding ───────────────────────────────────────────────────────────────

new-service: ## Scaffold a new backend service from ai-circus-template (usage: make new-service NAME=my-service)
	@[ -n "$(NAME)" ] || { echo "❌ usage: make new-service NAME=my-service"; exit 1; }
	@./scripts/new_service.sh "$(NAME)"

sync-shared: ## Rebuild+reinstall libs/shared in every service (run after editing libs/shared)
	@for dir in services/*/; do \
		if [ -f "$$dir/pyproject.toml" ]; then \
			echo "── $$dir ──"; \
			(cd "$$dir" && uv sync --reinstall-package ai-circus-shared) || exit 1; \
		fi; \
	done
	@echo "✓ ai-circus-shared resynced everywhere"

# ── QA across services ────────────────────────────────────────────────────────

check-all: ## Run `make check` inside every generated service
	@for dir in services/*/; do \
		if [ -f "$$dir/Makefile" ]; then \
			echo "── $$dir ──"; \
			$(MAKE) -C "$$dir" check || exit 1; \
		fi; \
	done
	@echo "✓ all services checked"

clean: ## Remove containers, volumes, and per-service build artifacts
	@docker compose down -v
	@for dir in services/*/ ui-react; do \
		[ -f "$$dir/Makefile" ] && $(MAKE) -C "$$dir" clean 2>/dev/null || true; \
	done
