# Root orchestration for ai-circus-framework. Each service under services/ and each
# UI has its own Makefile (generated by ai-circus-template) for `make check`/`make run`
# from inside that service's directory — this Makefile only orchestrates across them.

.DEFAULT_GOAL := help

ifneq (,$(wildcard .env))
    include .env
    export
endif

CYAN  := $(shell tput setaf 6 2>/dev/null)
RESET := $(shell tput sgr0 2>/dev/null)

.PHONY: help bootstrap up up-infra down logs pipeline new-service sync-shared check-all clean ollama-up

help: ## Show this help message
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS=":.*?## "}; {printf "  $(CYAN)%-18s$(RESET) %s\n", $$1, $$2}'

# ── Bootstrap ─────────────────────────────────────────────────────────────────

bootstrap: ## Create .env from .env.example if missing
	@if [ ! -f .env ] && [ -f .env.example ]; then echo "📝 Creating .env from .env.example..."; cp .env.example .env; fi
	@echo "✓ Edit .env (Logto/LLM/MinIO secrets) before running 'make up'"

# ── Compose lifecycle ─────────────────────────────────────────────────────────

up-infra: ## Start only the platform infra (postgres, logto, qdrant, minio, traefik)
	@docker compose up -d postgres logto qdrant minio traefik

up: ## Start the full platform (infra + all backend services + the UI)
	@docker compose up -d --build

down: ## Stop and remove all containers
	@docker compose down

logs: ## Tail logs for all running containers
	@docker compose logs -f --tail=200

pipeline: ## Run the one-shot churn ETL -> training pipeline, then (re)start prediction
	@docker compose up --build etl-tabular
	@docker compose up --build training
	@docker compose up -d --build prediction

ollama-up: ## Start the optional bundled Ollama (free, no-API-key LLM fallback; pulls llama3.2:3b, ~2GB, on first run)
	@docker compose --profile ollama up -d ollama ollama-pull

# ── Scaffolding ───────────────────────────────────────────────────────────────

new-service: ## Scaffold a new backend service from ai-circus-template (usage: make new-service NAME=my-service)
	@[ -n "$(NAME)" ] || { echo "❌ usage: make new-service NAME=my-service"; exit 1; }
	@./scripts/new_service.sh "$(NAME)"

sync-shared: ## Rebuild+reinstall libs/shared in every service (run after editing libs/shared)
	@for dir in services/*/; do \
		if [ -f "$$dir/pyproject.toml" ]; then \
			echo "── $$dir ──"; \
			(cd "$$dir" && uv sync --reinstall-package ai-circus-shared) || exit 1; \
		fi; \
	done
	@echo "✓ ai-circus-shared resynced everywhere"

# ── QA across services ────────────────────────────────────────────────────────

check-all: ## Run `make check` inside every generated service
	@for dir in services/*/; do \
		if [ -f "$$dir/Makefile" ]; then \
			echo "── $$dir ──"; \
			$(MAKE) -C "$$dir" check || exit 1; \
		fi; \
	done
	@echo "✓ all services checked"

clean: ## Remove containers, volumes, and per-service build artifacts
	@docker compose down -v
	@for dir in services/*/ ui-react; do \
		[ -f "$$dir/Makefile" ] && $(MAKE) -C "$$dir" clean 2>/dev/null || true; \
	done
