# Root orchestration for ai-circus-framework. Each service under services/ and each
# UI has its own Makefile (generated by ai-circus-template) for `make check`/`make run`
# from inside that service's directory — this Makefile only orchestrates across them.

.DEFAULT_GOAL := help

ifneq (,$(wildcard .env))
    include .env
    export
endif

CYAN  := $(shell tput setaf 6 2>/dev/null)
RESET := $(shell tput sgr0 2>/dev/null)

.PHONY: help bootstrap up up-infra generate-console-auth check-public-ready down logs pipeline new-service \
	sync-shared check-all clean ollama-up all reset-all wait-infra wait-services verify \
	data-platform-up data-platform-down \
	k3s-cluster k3s-build k3s-import k3s-secrets k3s-up k3s-wait k3s-pipeline k3s-verify k3s-down \
	k3s-all k3s-all-lite k3s-pause k3s-resume k3s-lite k3s-full k3s-resume-lite k3s-portforward k3s-portforward-stop \
	k3s-data-platform-up k3s-data-platform-down \
	dl-gpu-check dl-data dl-train dl-train-nlp dl-train-cv \
	k3s-dl-build k3s-dl-up k3s-dl-down k3s-dl-train k3s-dl-train-nlp k3s-dl-train-cv k3s-all-dl k3s-gpu-smoke

help: ## Show this help message
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS=":.*?## "}; {printf "  $(CYAN)%-18s$(RESET) %s\n", $$1, $$2}'

# ── Bootstrap ─────────────────────────────────────────────────────────────────

bootstrap: ## Create .env from .env.example, console.htpasswd from its .example (if missing), and infra/seaweedfs/s3.json from .env
	@if [ ! -f .env ] && [ -f .env.example ]; then echo "📝 Creating .env from .env.example..."; cp .env.example .env; fi
	@if [ ! -f infra/traefik/console.htpasswd ] && [ -f infra/traefik/console.htpasswd.example ]; then \
		echo "📝 Creating infra/traefik/console.htpasswd from its .example (demo credential — rotate with 'make generate-console-auth' before a public deployment)..."; \
		cp infra/traefik/console.htpasswd.example infra/traefik/console.htpasswd; \
	fi
	@./scripts/generate_seaweedfs_s3_config.sh
	@echo "✓ Edit .env (Keycloak/LLM/SeaweedFS secrets) before running 'make up'"

# ── Compose lifecycle ─────────────────────────────────────────────────────────

up-infra: ## Start only the platform infra (postgres, keycloak, qdrant, seaweedfs, valkey, traefik)
	@docker compose up -d postgres keycloak qdrant seaweedfs valkey traefik

up: ## Start the full platform (infra + all backend services + the UI)
	@mkdir -p demo/themes
	@docker compose up -d --build

down: ## Stop and remove all containers
	@docker compose down

logs: ## Tail logs for all running containers
	@docker compose logs -f --tail=200

pipeline: ## Run the one-shot ETL -> training pipeline (every tabular_ml scenario in SCENARIOS, empty/unset = all), then (re)start prediction
	@docker compose up --build etl-tabular
	@docker compose up --build training
	@docker compose up -d --build prediction

data-platform-up: ## Start the optional Data Platform profile (currently: Kafka event streaming) — off by default, ~768MB RAM
	@docker compose --profile data-platform up -d --build kafka
	@echo "✓ kafka up — data-platform-manager will start publishing/reading real events against it"

data-platform-down: ## Stop the optional Data Platform profile's containers (state is kept — see docker-compose.yml's kafka-data volume)
	@docker compose --profile data-platform stop kafka

ollama-up: ## Start the optional bundled Ollama (free, no-API-key LLM fallback; pulls llama3.2:3b, ~2GB, on first run)
	@docker compose --profile ollama up -d ollama ollama-pull

# ── Public deployment (any public VM, or minikube behind a public Ingress) — no
# separate compose file or `up` variant: `make up` already serves both
# local dev and a real deployment, differentiated purely by .env (same as
# ADMIN_API_KEY/OBJECT_STORE_SECRET_KEY/etc. always have been). See README "Public
# deployment" for the full checklist; the two commands below cover the parts that
# are easy to forget.

generate-console-auth: ## (Re)generate infra/traefik/console.htpasswd — the Basic Auth credential gating admin.keycloak/console.objectstore/mlflow — usage: make generate-console-auth [CONSOLE_USER=admin] [CONSOLE_PASSWORD=...] (omit the password for a random one)
	@./scripts/generate_console_auth.sh "$(CONSOLE_USER)" "$(CONSOLE_PASSWORD)"

check-public-ready: ## Verify .env/console.htpasswd don't still hold shipped demo values before a public deployment (does not start/stop anything)
	@ok=1; \
	if [ "$${DEPLOYMENT_TARGET:-local}" != "public" ]; then \
		echo "❌ DEPLOYMENT_TARGET is not 'public' in .env — every service's boot-time guard is a no-op until it is"; ok=0; \
	fi; \
	if [ "$${ADMIN_API_KEY:-angel2026}" = "angel2026" ]; then \
		echo "❌ ADMIN_API_KEY is still the shipped demo default — rotate it or blank it in .env"; ok=0; \
	fi; \
	if [ "$${ENGINEERING_DEMO_API_KEY:-}" = "ai-circus-engineering-2026" ]; then \
		echo "❌ ENGINEERING_DEMO_API_KEY is still the shipped demo default — rotate it or blank it in .env"; ok=0; \
	fi; \
	if [ "$${AUTH_DISABLED:-false}" = "true" ]; then \
		echo "❌ AUTH_DISABLED=true in .env — this bypasses Keycloak entirely, never set it for a public deployment"; ok=0; \
	fi; \
	if [ ! -f infra/traefik/console.htpasswd ]; then \
		echo "❌ infra/traefik/console.htpasswd is missing — run 'make generate-console-auth'"; ok=0; \
	elif [ -f infra/traefik/console.htpasswd.example ] && cmp -s infra/traefik/console.htpasswd infra/traefik/console.htpasswd.example; then \
		echo "❌ infra/traefik/console.htpasswd still holds the shipped demo credential — run 'make generate-console-auth'"; ok=0; \
	fi; \
	if [ -f infra/seaweedfs/s3.json.example ] && cmp -s infra/seaweedfs/s3.json infra/seaweedfs/s3.json.example 2>/dev/null; then \
		echo "❌ infra/seaweedfs/s3.json still holds the shipped demo credential — set OBJECT_STORE_ACCESS_KEY/SECRET_KEY in .env then run './scripts/generate_seaweedfs_s3_config.sh'"; ok=0; \
	fi; \
	if [ "$$ok" = "1" ]; then echo "✓ looks ready for a public deployment — run 'make up' (or 'make all') on the target host"; else exit 1; fi

# ── One-shot setup / troubleshooting ────────────────────────────────────────────
#
# `all` exists because the individual steps above have a real ordering dependency
# (`up` before `pipeline`, both after `up-infra`'s containers are actually healthy —
# not just "started") that's easy to get wrong on a fresh clone, especially on a
# machine other than the one the repo was first set up on. `verify` reproduces the
# exact request the browser's login screen makes, so a "Failed to fetch" in the UI
# can be diagnosed here, with logs, before it's ever a browser mystery.

all: ## One-shot: bootstrap .env, start infra+services, run both pipelines, verify the admin tenant end-to-end (safe to re-run any time; use this instead of the individual up-infra/up/pipeline steps unless you need finer control)
	@$(MAKE) bootstrap
	@$(MAKE) up-infra
	@$(MAKE) wait-infra
	@$(MAKE) up
	@$(MAKE) wait-services
	@$(MAKE) pipeline
	@echo "▶ vectorizing the conversational_rag scenario's reference docs..."
	@docker compose up --build etl-vectorize
	@$(MAKE) verify
	@echo ""
	@echo "🎉 ai-circus-framework is up — open http://aiopen.localhost, pick 'admin' from the User dropdown, and use the ADMIN_API_KEY from .env as the password."
	@if [ -z "$$OPENAI_API_KEY$$GOOGLE_API_KEY$$AZURE_OPENAI_API_KEY$$DEEPSEEK_API_KEY$$GROQ_API_KEY$$OPENROUTER_API_KEY$$ANTHROPIC_API_KEY" ]; then \
		echo "ℹ️  No LLM provider key set in .env — chat (assistant/rag-agent) won't answer yet."; \
		echo "   Add one provider key to .env then 'make up', or run 'make ollama-up' for a free local fallback."; \
	fi

reset-all: ## Nuke containers + volumes + per-service build artifacts, then rebuild fresh via `make all` — the fastest way back to a known-good state, and what to run before sharing this repo so it's proven from a clean slate
	@echo "🧹 tearing down containers + volumes (postgres/keycloak/qdrant/seaweedfs data all reset)..."
	@docker compose down -v
	@$(MAKE) all

wait-infra: ## Wait for postgres+keycloak to report healthy (internal step of `make all`; also handy standalone if `make up-infra` seems stuck)
	@echo "⏳ waiting for postgres..."
	@i=0; until [ "$$(docker compose ps postgres --format '{{.Health}}' 2>/dev/null)" = "healthy" ]; do \
		i=$$((i+1)); [ $$i -ge 60 ] && { echo "❌ postgres never became healthy — check: docker compose logs postgres"; exit 1; }; \
		sleep 2; \
	done
	@echo "⏳ waiting for keycloak (first boot imports the realm — can take a couple of minutes)..."
	@i=0; until [ "$$(docker compose ps keycloak --format '{{.Health}}' 2>/dev/null)" = "healthy" ]; do \
		i=$$((i+1)); [ $$i -ge 90 ] && { echo "❌ keycloak never became healthy — check: docker compose logs keycloak"; exit 1; }; \
		sleep 2; \
	done
	@echo "✓ infra healthy"

wait-services: ## Wait for platform-registry and every Traefik-routed backend to answer real requests (internal step of `make all`)
	@echo "⏳ waiting for platform-registry..."
	@i=0; until curl -sf "http://localhost:$${PLATFORM_REGISTRY_PORT:-8010}/healthz" >/dev/null 2>&1; do \
		i=$$((i+1)); [ $$i -ge 60 ] && { echo "❌ platform-registry never came up — check: docker compose logs platform-registry"; exit 1; }; \
		sleep 2; \
	done
	@for host in prediction assistant rag-agent; do \
		echo "⏳ waiting for $$host.localhost (via Traefik)..."; \
		i=0; until curl -sf "http://$$host.localhost/healthz" >/dev/null 2>&1; do \
			i=$$((i+1)); \
			[ $$i -ge 60 ] && { echo "❌ $$host.localhost never answered — check: docker compose logs $$host, and that 'getent hosts $$host.localhost' resolves to 127.0.0.1"; exit 1; }; \
			sleep 2; \
		done; \
	done
	@echo "⏳ waiting for aiopen.localhost..."
	@i=0; until curl -sf "http://aiopen.localhost/" >/dev/null 2>&1; do \
		i=$$((i+1)); [ $$i -ge 60 ] && { echo "❌ aiopen.localhost never answered — check: docker compose logs ui-react, and that port 80 isn't already used by something else on this machine"; exit 1; }; \
		sleep 2; \
	done
	@echo "⏳ waiting for langfuse.localhost (first boot migrates Postgres + ClickHouse — a few minutes on a laptop)..."
	@i=0; until curl -sf "http://langfuse.localhost/api/public/health" >/dev/null 2>&1; do \
		i=$$((i+1)); [ $$i -ge 150 ] && { echo "❌ langfuse.localhost never answered — check: docker compose logs langfuse-web clickhouse"; exit 1; }; \
		sleep 2; \
	done
	@echo "✓ all services answering"

verify: ## Curl-check the admin (and, if configured, engineering-demo) tenant end-to-end — the exact calls the login screen makes — catches "Failed to fetch"-class setup issues before you open a browser
	@echo "🔎 verifying admin tenant end-to-end..."
	@key="$${ADMIN_API_KEY:-angel2026}"; \
	code=$$(curl -s -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $$key" "http://localhost:$${PLATFORM_REGISTRY_PORT:-8010}/llm-settings/active-model"); \
	if [ "$$code" = "401" ]; then \
		echo "❌ ADMIN_API_KEY in .env doesn't match what platform-registry is running with — after editing .env, run 'make up' to recreate it"; exit 1; \
	fi; \
	echo "  ✓ admin key accepted by platform-registry ($$code)"
	@key="$${ADMIN_API_KEY:-angel2026}"; \
	n=$$(curl -s -H "Authorization: Bearer $$key" "http://localhost:$${PLATFORM_REGISTRY_PORT:-8010}/entitlements/admin" | grep -o '"slug"' | wc -l); \
	if [ "$$n" -gt 0 ]; then echo "  ✓ admin tenant is entitled to $$n scenario(s)"; \
	else echo "❌ admin tenant has 0 entitled scenarios — scenario seeding may have failed, check: docker compose logs platform-registry"; exit 1; fi
	@for host in prediction assistant rag-agent; do \
		code=$$(curl -s -o /dev/null -w '%{http_code}' "http://$$host.localhost/healthz"); \
		if [ "$$code" = "200" ]; then echo "  ✓ $$host.localhost reachable ($$code)"; \
		else echo "❌ $$host.localhost -> $$code — this is the exact failure behind a browser 'Failed to fetch'. Check: docker compose ps, docker compose logs $$host, and 'getent hosts $$host.localhost'"; exit 1; fi; \
	done
	@code=$$(curl -s -o /dev/null -w '%{http_code}' "http://aiopen.localhost/"); \
	if [ "$$code" = "200" ]; then echo "  ✓ aiopen.localhost reachable ($$code)"; \
	else echo "❌ aiopen.localhost -> $$code — check: docker compose logs ui-react, and that port 80 isn't already used by something else on this machine"; exit 1; fi
	@code=$$(curl -s -o /dev/null -w '%{http_code}' "http://langfuse.localhost/api/public/health"); \
	if [ "$$code" = "200" ]; then echo "  ✓ langfuse.localhost reachable ($$code) — GenAI monitor"; \
	else echo "❌ langfuse.localhost -> $$code — check: logs of langfuse-web / clickhouse (first boot runs migrations for a few minutes)"; exit 1; fi
	@code=$$(curl -s -o /dev/null -w '%{http_code}' "http://mlflow.localhost/health"); \
	if [ "$$code" = "401" ]; then echo "  ✓ mlflow.localhost reachable ($$code, admin-basicauth in front) — MLOps monitor"; \
	else echo "❌ mlflow.localhost -> $$code (expected 401 from the admin-basicauth gate) — check: logs of mlflow"; exit 1; fi
	@echo "✓ admin tenant verified — http://aiopen.localhost is ready for the 'admin' User dropdown login"
	@demo_key="$${ENGINEERING_DEMO_API_KEY:-}"; \
	if [ -z "$$demo_key" ]; then \
		echo "ℹ️  ENGINEERING_DEMO_API_KEY not set in .env — skipping engineering-demo tenant checks"; \
		exit 0; \
	fi; \
	echo "🔎 verifying engineering-demo tenant is scoped correctly..."; \
	code=$$(curl -s -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $$demo_key" "http://localhost:$${PLATFORM_REGISTRY_PORT:-8010}/auth/verify-engineering-demo-key"); \
	if [ "$$code" != "200" ]; then \
		echo "❌ ENGINEERING_DEMO_API_KEY in .env doesn't match what platform-registry is running with ($$code) — after editing .env, run 'make up' to recreate it"; exit 1; \
	fi; \
	echo "  ✓ engineering demo key accepted by platform-registry ($$code)"; \
	slugs=$$(curl -s -H "Authorization: Bearer $$demo_key" "http://localhost:$${PLATFORM_REGISTRY_PORT:-8010}/entitlements/engineering-demo" | grep -o '"slug":"[a-z_]*"' | sort); \
	expected=$$(printf '"slug":"electric_motor"\n"slug":"energy_building"\n"slug":"mpm"'); \
	if [ "$$slugs" = "$$expected" ]; then \
		echo "  ✓ engineering-demo tenant is entitled to exactly mpm/electric_motor/energy_building"; \
	else \
		echo "❌ engineering-demo tenant entitlements don't match — expected mpm/electric_motor/energy_building, got:"; echo "$$slugs"; exit 1; \
	fi; \
	code=$$(curl -s -o /dev/null -w '%{http_code}' -X POST -H "Authorization: Bearer $$demo_key" -H "Content-Type: application/json" -d '{"records":[]}' "http://prediction.localhost/predict/churn"); \
	if [ "$$code" = "403" ]; then \
		echo "  ✓ engineering-demo key correctly denied access to an out-of-scope scenario (churn -> 403)"; \
	else \
		echo "❌ engineering-demo key was NOT denied access to churn (got $$code, expected 403) — scoping enforcement is broken"; exit 1; \
	fi; \
	echo "✓ engineering-demo tenant verified — scoped to exactly mpm/electric_motor/energy_building"

# ── k3s (local single-node, via k3d — see k8s/README.md) ───────────────────────
# Dev-parity only: same *.localhost hostnames/routing as docker-compose, on a local
# k3d cluster instead. Not a production/multi-node setup — no registry, no
# imagePullSecrets; images are built locally and imported straight into k3d's
# containerd. Run these roughly in order: cluster -> build -> import -> secrets -> up
# -> wait -> (pipeline) -> verify.

K3S_CLUSTER ?= ai-circus
K3S_IMAGES   = platform-registry etl-tabular prediction llm-gateway assistant training etl-vectorize rag-agent form-agent agui-voice data-platform-manager
K3S_PORTFORWARD_PID = /tmp/k3s-portforward-$(K3S_CLUSTER).pid
# Deployments `k3s-lite`/`k3s-resume-lite` scale to 0 — the heaviest pods the day-to-day demo never
# touches (measured RSS on a running cluster: agui-voice ~830Mi, mlflow ~350Mi). Langfuse
# (+ clickhouse/valkey) and data-platform-manager (the admin Platform health dashboard) deliberately
# stay on. Override per call to trim further, e.g. K3S_LITE_SKIP="mlflow agui-voice langfuse-web langfuse-worker".
K3S_LITE_SKIP ?= mlflow agui-voice

K3S_SUBNET   ?=  # optional, e.g. 172.28.0.0/16 — pins static node IPs so a Docker/host restart can't swap them (k3d marks --subnet experimental; see k8s/README.md)
K3S_VERSION  ?= v1.35.5-k3s1
# auto: a GPU-enabled cluster whenever Docker can pass the host GPU through (NVIDIA
# Container Toolkit — `sudo ./scripts/setup_gpu_containers.sh`); 1 forces it, 0 never.
K3S_GPU      ?= auto

k3s-cluster: ## Create the local k3d cluster (idempotent) — port 80 for Traefik, ./scenarios bind-mounted for hostPath volumes; K3S_SUBNET=… pins node IPs; K3S_GPU=auto|1|0 adds the host GPU (infra/k3s-gpu/)
	@./scripts/k3s_cluster_create.sh "$(K3S_CLUSTER)" "$(strip $(K3S_GPU))" "$(strip $(K3S_VERSION))" "$(strip $(K3S_SUBNET))"

k3s-gpu-smoke: ## Prove a pod can use the cluster GPU (nvidia RuntimeClass + device plugin): runs nvidia-smi once — needs a K3S_GPU cluster
	@kubectl -n ai-circus delete pod gpu-smoke --ignore-not-found >/dev/null
	@kubectl apply -f k8s/jobs/gpu-smoke-pod.yaml >/dev/null
	@kubectl -n ai-circus wait --for=jsonpath='{.status.phase}'=Succeeded pod/gpu-smoke --timeout=180s \
		|| { kubectl -n ai-circus describe pod gpu-smoke | tail -15; exit 1; }
	@kubectl -n ai-circus logs gpu-smoke
	@kubectl -n ai-circus delete pod gpu-smoke --ignore-not-found >/dev/null
	@echo "✓ the cluster GPU works — in-cluster deep-learning training will request it"

k3s-build: ## Build every service image locally (same Dockerfiles docker-compose uses), tagged ai-circus/<service>:local
	@mkdir -p demo/themes
	@for svc in $(K3S_IMAGES); do \
		echo "── ai-circus/$$svc:local ──"; \
		docker build -f "services/$$svc/Dockerfile" -t "ai-circus/$$svc:local" . || exit 1; \
	done
	@echo "── ai-circus/mlflow:local (infra/mlflow/Dockerfile — MLOps monitor) ──"
	@docker build -f infra/mlflow/Dockerfile -t ai-circus/mlflow:local infra/mlflow || exit 1
	@docker build -f ui-react/Dockerfile -t ai-circus/ui-react:local \
		--build-arg VITE_KEYCLOAK_ISSUER="$(VITE_KEYCLOAK_ISSUER)" \
		--build-arg VITE_KEYCLOAK_CLIENT_ID="$(if $(VITE_KEYCLOAK_CLIENT_ID),$(VITE_KEYCLOAK_CLIENT_ID),ui-react)" \
		--build-arg VITE_KEYCLOAK_AUDIENCE="$(VITE_KEYCLOAK_AUDIENCE)" \
		--build-arg VITE_DEV_MODE="$(if $(DEV_MODE),$(DEV_MODE),false)" \
		--build-arg VITE_DEV_ORG_ID="$(if $(DEV_ORG_ID),$(DEV_ORG_ID),demo)" \
		.
	@echo "✓ all images built"

k3s-import: ## Import every ai-circus/*:local image into the k3d cluster's containerd
	@for svc in $(K3S_IMAGES) ui-react mlflow; do \
		k3d image import "ai-circus/$$svc:local" -c "$(K3S_CLUSTER)" || exit 1; \
	done
	@echo "✓ all images imported into k3d cluster '$(K3S_CLUSTER)'"

k3s-secrets: ## Generate the app-env/traefik-basicauth/seaweedfs-s3-config k8s Secrets from .env/infra — never committed, re-run any time those change
	@./scripts/k3s_generate_secrets.sh

k3s-up: ## Apply every manifest under k8s/base (namespace, infra, backend services, ingress)
	@kubectl apply -k k8s/base
	@echo "✓ k8s/base applied — 'make k3s-wait' to wait for it to actually be ready"

k3s-wait: ## Wait for postgres/qdrant/seaweedfs and every backend Deployment to report Ready
	@echo "⏳ waiting for postgres/qdrant/seaweedfs..."
	@kubectl -n ai-circus rollout status statefulset/postgres --timeout=180s
	@kubectl -n ai-circus rollout status statefulset/qdrant --timeout=60s
	@kubectl -n ai-circus rollout status statefulset/seaweedfs --timeout=60s
	@echo "⏳ waiting for keycloak (first boot imports the realm — can take a couple of minutes)..."
	@kubectl -n ai-circus rollout status deployment/keycloak --timeout=180s
	@for svc in platform-registry llm-gateway prediction assistant rag-agent form-agent agui-voice data-platform-manager ui-react; do \
		echo "⏳ waiting for $$svc..."; \
		kubectl -n ai-circus rollout status deployment/$$svc --timeout=120s || exit 1; \
	done
	@echo "⏳ waiting for the observability stack (Langfuse's first boot migrates Postgres + ClickHouse — a few minutes on a laptop)..."
	@kubectl -n ai-circus rollout status statefulset/clickhouse --timeout=180s
	@for svc in mlflow langfuse-web langfuse-worker; do \
		echo "⏳ waiting for $$svc..."; \
		kubectl -n ai-circus rollout status deployment/$$svc --timeout=300s || exit 1; \
	done
	@echo "✓ all pods ready"
	@$(MAKE) k3s-portforward

k3s-pipeline: ## Run the one-shot ETL -> training pipeline (every tabular_ml scenario) as k8s Jobs (mirrors `make pipeline`) — REQUIRED before any tabular_ml scenario can serve a prediction; a fresh/recreated cluster has no trained models until this runs
	@kubectl -n ai-circus delete job etl-tabular training --ignore-not-found
	@kubectl apply -f k8s/jobs/etl-tabular-job.yaml
	@kubectl -n ai-circus wait --for=condition=complete job/etl-tabular --timeout=300s
	@kubectl apply -f k8s/jobs/training-job.yaml
	@kubectl -n ai-circus wait --for=condition=complete job/training --timeout=600s
	@kubectl -n ai-circus rollout restart deployment/prediction
	@echo "✓ tabular_ml pipeline complete (every scenario in SCENARIOS, empty/unset = all)"

k3s-verify: ## Port-forward platform-registry, then reuse `make verify`'s curl checks unchanged (same *.localhost + localhost:$${PLATFORM_REGISTRY_PORT:-8010} assertions, now against k3d's Traefik)
	@kubectl -n ai-circus port-forward svc/platform-registry "$${PLATFORM_REGISTRY_PORT:-8010}:8000" >/tmp/k3s-verify-port-forward.log 2>&1 & \
	pf_pid=$$!; \
	trap "kill $$pf_pid 2>/dev/null" EXIT; \
	sleep 2; \
	$(MAKE) verify

k3s-down: k3s-portforward-stop ## Delete every applied k8s/base manifest (StatefulSet PVCs are retained by default — delete the k3d cluster entirely for a full wipe: `k3d cluster delete $(K3S_CLUSTER)`)
	@kubectl delete -k k8s/base --ignore-not-found

k3s-all: k3s-cluster k3s-build k3s-import k3s-secrets k3s-up k3s-wait ## One-shot: cluster -> build -> import -> secrets -> up -> wait (run `make k3s-pipeline` yourself afterward if you need the churn ETL/training data)
	@echo "✓ k3s cluster '$(K3S_CLUSTER)' is up — http://aiopen.localhost"

k3s-all-lite: k3s-cluster k3s-build k3s-import k3s-secrets k3s-up k3s-lite k3s-wait ## `k3s-all`, but the K3S_LITE_SKIP pods (default mlflow, agui-voice) are scaled to 0 right after `k3s-up` so `k3s-wait` never waits on them — images are still built/imported, so `make k3s-full` works later without a rebuild
	@echo "✓ k3s cluster '$(K3S_CLUSTER)' is up in lite mode — http://aiopen.localhost ('make k3s-full' brings the skipped pods back)"

k3s-data-platform-up: ## Apply the optional Data Platform profile (k8s/data-platform/ — currently: Kafka), NOT part of `k3s-up`/`k3s-down`
	@kubectl apply -f k8s/data-platform/kafka.yaml
	@kubectl -n ai-circus rollout status statefulset/kafka --timeout=120s
	@echo "✓ kafka up in k3s — data-platform-manager will start publishing/reading real events against it"

k3s-data-platform-down: ## Delete the optional Data Platform profile's k8s resources (its PVC is retained by default, same as postgres/qdrant)
	@kubectl delete -f k8s/data-platform/kafka.yaml --ignore-not-found

k3s-pause: k3s-portforward-stop ## Stop the k3d cluster's containers to free CPU/RAM while keeping all cluster state (pods, volumes) — resume with `make k3s-resume`
	@k3d cluster stop "$(K3S_CLUSTER)"
	@echo "✓ k3d cluster '$(K3S_CLUSTER)' stopped — resume with 'make k3s-resume'"

k3s-resume: ## Start a previously paused k3d cluster back up
	@k3d cluster start "$(K3S_CLUSTER)"
	@echo "✓ k3d cluster '$(K3S_CLUSTER)' started — 'make k3s-wait' to confirm pods are Ready (also restarts the platform-registry port-forward)"

k3s-lite: ## Scale the rarely-used Deployments in K3S_LITE_SKIP (default: mlflow agui-voice) to 0 replicas on the running cluster to save RAM — Langfuse stays on; undo with `make k3s-full`
	@for svc in $(K3S_LITE_SKIP); do \
		kubectl -n ai-circus scale deployment/$$svc --replicas=0 || exit 1; \
	done
	@echo "✓ lite mode — scaled to 0: $(K3S_LITE_SKIP) (voice mode / MLflow will be unavailable; 'make k3s-full' restores)"

k3s-full: ## Scale every Deployment `k3s-lite` turned off back to 1 replica (the full k8s/base set again)
	@for svc in $(K3S_LITE_SKIP); do \
		kubectl -n ai-circus scale deployment/$$svc --replicas=1 || exit 1; \
	done
	@echo "✓ full mode — scaled back to 1: $(K3S_LITE_SKIP) — 'make k3s-wait' to confirm they are Ready"

k3s-resume-lite: k3s-resume k3s-lite k3s-wait ## Resume a paused cluster WITHOUT the heavy rarely-used pods (default skips mlflow and agui-voice — ~1.2 GB less RSS), then wait for the rest to be Ready
	@echo "✓ k3d cluster '$(K3S_CLUSTER)' resumed in lite mode — http://aiopen.localhost ('make k3s-full' brings the skipped pods back)"

k3s-portforward: ## Start (or restart) a standing background port-forward to platform-registry so the browser can reach it directly — auto-run by k3s-wait, safe to re-run any time
	@if [ -f "$(K3S_PORTFORWARD_PID)" ] && kill -0 "$$(cat $(K3S_PORTFORWARD_PID))" 2>/dev/null; then \
		kill "$$(cat $(K3S_PORTFORWARD_PID))" 2>/dev/null; sleep 1; \
	fi
	@rm -f "$(K3S_PORTFORWARD_PID)"
	@nohup kubectl -n ai-circus port-forward svc/platform-registry "$${PLATFORM_REGISTRY_PORT:-8010}:8000" >/tmp/k3s-portforward-$(K3S_CLUSTER).log 2>&1 & \
		echo $$! > "$(K3S_PORTFORWARD_PID)"
	@sleep 1
	@echo "✓ platform-registry port-forward running in background (PID $$(cat $(K3S_PORTFORWARD_PID))) — http://localhost:$${PLATFORM_REGISTRY_PORT:-8010}"

k3s-portforward-stop: ## Stop the standing platform-registry port-forward started by k3s-portforward/k3s-wait
	@if [ -f "$(K3S_PORTFORWARD_PID)" ]; then \
		kill "$$(cat $(K3S_PORTFORWARD_PID))" 2>/dev/null || true; \
		rm -f "$(K3S_PORTFORWARD_PID)"; \
		echo "✓ platform-registry port-forward stopped"; \
	fi

# ── Deep learning scenarios (optional — NEVER part of `make all`/`k3s-all`) ─────
# `kind: deep_learning` scenarios (scenarios/symptom_triage, scenarios/chest_xray_pneumonia)
# fine-tune Hugging Face models: minutes on a GPU, far longer on a CPU — so training only
# ever runs from these explicit targets (or the admin console's Platform → Deep Learning
# tab). `dl-train-*` trains on THIS machine (its GPU, if any) and publishes to the running
# stack's SeaweedFS; the k3s-dl-* targets below deploy the separate dl-inference service.

DL_SCENARIO_NLP ?= symptom_triage
DL_SCENARIO_CV  ?= chest_xray_pneumonia

dl-gpu-check: ## Report whether this machine has an NVIDIA GPU dl-train-* can use (and what the k3s cluster exposes)
	@if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then \
		echo "⚡ host GPU: $$(nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader | head -1) — dl-train-* will fine-tune on it"; \
	else echo "ℹ️  no host NVIDIA GPU — dl-train-* would use each scenario's reduced CPU budget (asks first)"; fi
	@gpus=$$(kubectl get nodes -o jsonpath='{range .items[*]}{.status.allocatable.nvidia\.com/gpu}{"\n"}{end}' 2>/dev/null | awk '{s+=$$1} END {print s+0}'); \
	echo "   k3s cluster GPUs (nvidia.com/gpu allocatable): $${gpus:-0} — in-cluster training (k3s-dl-train-*, admin console) uses CPU unless > 0"

dl-data: ## Download + checksum-verify every deep_learning scenario's public data into SeaweedFS (no training; SCENARIOS=… to narrow)
	@./scripts/dl_train_host.sh --download-only "$(SCENARIOS)"

dl-train: ## Fine-tune every deep_learning scenario on this machine (GPU if present; CPU asks first) and publish to SeaweedFS — SCENARIOS=… to narrow
	@./scripts/dl_train_host.sh "$(SCENARIOS)"

dl-train-nlp: ## Fine-tune the NLP scenario (BioClinical ModernBERT, symptom triage) on this machine's GPU
	@./scripts/dl_train_host.sh "$(DL_SCENARIO_NLP)"

dl-train-cv: ## Fine-tune the computer-vision scenario (ConvNeXt V2, chest X-ray) on this machine's GPU
	@./scripts/dl_train_host.sh "$(DL_SCENARIO_CV)"

# dl-training image's torch build: auto = the CUDA build when the cluster advertises
# nvidia.com/gpu (it still runs on CPU), else the ~1 GB smaller CPU build; or force cpu|gpu.
DL_TRAINING_TORCH ?= auto
DL_TRAINING_TORCH_RESOLVED = $(if $(filter auto,$(strip $(DL_TRAINING_TORCH))),$(shell kubectl get nodes -o jsonpath='{range .items[*]}{.status.allocatable.nvidia\.com/gpu}{"\n"}{end}' 2>/dev/null | awk '{s+=$$1} END {print (s>0) ? "gpu" : "cpu"}'),$(strip $(DL_TRAINING_TORCH)))

k3s-dl-build: ## Build + import the Deep Learning images (dl-inference, dl-training) into k3d — separate from k3s-build so the ~2 GB torch image is opt-in
	@docker build -f services/dl-inference/Dockerfile -t ai-circus/dl-inference:local . || exit 1
	@docker build -f services/dl-training/Dockerfile --build-arg DL_TRAINING_TORCH=$(DL_TRAINING_TORCH_RESOLVED) -t ai-circus/dl-training:local . || exit 1
	@for img in dl-inference dl-training; do k3d image import "ai-circus/$$img:local" -c "$(K3S_CLUSTER)" || exit 1; done
	@echo "✓ Deep Learning images built + imported (dl-training torch=$(DL_TRAINING_TORCH_RESOLVED))"

k3s-dl-up: ## Deploy the optional Deep Learning overlay (k8s/deep-learning/: dl-inference) and wait for it — models come from `make dl-train*` / k3s-dl-train-*
	@kubectl apply -k k8s/deep-learning
	@kubectl -n ai-circus rollout status deployment/dl-inference --timeout=180s
	@echo "✓ dl-inference up — http://dl-inference.localhost (healthz); the healthcare scenarios appear in http://aiopen.localhost"

k3s-dl-down: ## Remove the Deep Learning overlay (trained models stay in SeaweedFS)
	@kubectl delete -k k8s/deep-learning --ignore-not-found

k3s-dl-train: ## Train ONE deep_learning scenario as an in-cluster Job (CPU budget unless the cluster exposes a GPU) — usage: make k3s-dl-train SCENARIO=<slug>
	@[ -n "$(SCENARIO)" ] || { echo "❌ usage: make k3s-dl-train SCENARIO=<deep_learning slug>"; exit 1; }
	@job="dl-training-$$(echo '$(SCENARIO)' | tr '_' '-')"; \
	kubectl -n ai-circus delete job "$$job" --ignore-not-found; \
	sed -e "s/__JOB_NAME__/$$job/" -e "s/__SCENARIOS__/$(SCENARIO)/g" k8s/jobs/dl-training-job.yaml | kubectl apply -f -; \
	echo "⏳ $$job running (logs: kubectl -n ai-circus logs -f job/$$job)"; \
	kubectl -n ai-circus wait --for=condition=complete "job/$$job" --timeout=3600s

k3s-dl-train-nlp: ## In-cluster Job for the NLP scenario (see k3s-dl-train)
	@$(MAKE) --no-print-directory k3s-dl-train SCENARIO=$(DL_SCENARIO_NLP)

k3s-dl-train-cv: ## In-cluster Job for the computer-vision scenario (see k3s-dl-train)
	@$(MAKE) --no-print-directory k3s-dl-train SCENARIO=$(DL_SCENARIO_CV)

k3s-all-dl: k3s-all k3s-dl-build k3s-dl-up ## `k3s-all` + the Deep Learning overlay (no training — run `make dl-train` on a GPU host, or the admin console's Train button)
	@echo "✓ k3s cluster '$(K3S_CLUSTER)' is up with the Deep Learning overlay — train models with 'make dl-train' (GPU) if not done yet"

# ── Scaffolding ───────────────────────────────────────────────────────────────

new-service: ## Scaffold a new backend service from ai-circus-template (usage: make new-service NAME=my-service)
	@[ -n "$(NAME)" ] || { echo "❌ usage: make new-service NAME=my-service"; exit 1; }
	@./scripts/new_service.sh "$(NAME)"

sync-shared: ## Rebuild+reinstall libs/shared in every service (run after editing libs/shared)
	@for dir in services/*/; do \
		if [ -f "$$dir/pyproject.toml" ]; then \
			echo "── $$dir ──"; \
			(cd "$$dir" && uv sync --reinstall-package ai-circus-shared) || exit 1; \
		fi; \
	done
	@echo "✓ ai-circus-shared resynced everywhere"

# ── QA across services ────────────────────────────────────────────────────────

check-all: ## Run `make check` inside every generated service
	@for dir in services/*/; do \
		if [ -f "$$dir/Makefile" ]; then \
			echo "── $$dir ──"; \
			$(MAKE) -C "$$dir" check || exit 1; \
		fi; \
	done
	@echo "✓ all services checked"

clean: ## Remove containers, volumes, and per-service build artifacts
	@docker compose down -v
	@for dir in services/*/ ui-react; do \
		[ -f "$$dir/Makefile" ] && $(MAKE) -C "$$dir" clean 2>/dev/null || true; \
	done
