#!/usr/bin/env bash
# Standing `kubectl port-forward` to platform-registry — the one backend the browser reaches
# outside Traefik (k8s/README.md "Standing port-forward"). `make k3s-portforward` (auto-run by
# `make k3s-wait`), `make k3s-portforward-stop`, `make k3s-portforward-uninstall`.
#
# Where systemd runs a per-user manager (native Linux; WSL with `systemd=true` in
# /etc/wsl.conf) the port-forward is a systemd *user* service: enabled at boot (with lingering,
# so no login is needed) and restarted 5 s after kubectl exits — which kubectl does whenever
# the platform-registry pod restarts, or while the cluster isn't up yet after a reboot. So it
# survives reboots and pod restarts with nothing to re-run; without it, every reboot ended in
# "Failed to fetch" until someone ran `make k3s-portforward` again.
# Elsewhere (no user systemd, or K3S_PORTFORWARD_SERVICE=0) it falls back to a plain
# background process + PID file, which dies with the machine.
#
# Usage: scripts/k3s_portforward.sh start|stop|uninstall|status <cluster> [port]
set -euo pipefail

ACTION="${1:?usage: $0 start|stop|uninstall|status <cluster> [port]}"
CLUSTER="${2:?cluster name required}"
PORT="${3:-8010}"
UNIT="ai-circus-portforward-${CLUSTER}.service"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT_FILE="$UNIT_DIR/$UNIT"
PID_FILE="/tmp/k3s-portforward-${CLUSTER}.pid"
LOG_FILE="/tmp/k3s-portforward-${CLUSTER}.log"

use_service() {
    [ "${K3S_PORTFORWARD_SERVICE:-1}" != 0 ] && systemctl --user show-environment >/dev/null 2>&1
}

stop_background() {  # the fallback's process (also what older `make k3s-portforward` runs left behind)
    if [ -f "$PID_FILE" ]; then
        kill "$(cat "$PID_FILE")" 2>/dev/null || true
        rm -f "$PID_FILE"
    fi
}

wait_for_port() {
    for _ in $(seq 1 20); do
        (exec 3<>"/dev/tcp/127.0.0.1/$PORT") 2>/dev/null && return 0
        sleep 0.5
    done
    return 1
}

write_unit() {
    local kubectl_bin
    kubectl_bin="$(command -v kubectl)" || { echo "❌ kubectl not found on PATH" >&2; exit 1; }
    mkdir -p "$UNIT_DIR"
    # Absolute kubectl path + explicit kubeconfig/context: a user service has neither this
    # shell's PATH nor its current-context, and must never port-forward into another cluster.
    cat >"$UNIT_FILE" <<EOF
# Generated by ai-circus-framework scripts/k3s_portforward.sh — \`make k3s-portforward-uninstall\` removes it.
[Unit]
Description=ai-circus: platform-registry port-forward (k3d cluster ${CLUSTER}) on localhost:${PORT}
Documentation=https://github.com/angelmtenor/ai-circus-framework/blob/main/k8s/README.md
# Never give up: at boot Docker (and so the cluster) comes up after the user manager does.
StartLimitIntervalSec=0

[Service]
Environment=KUBECONFIG=${KUBECONFIG:-$HOME/.kube/config}
ExecStart=${kubectl_bin} --context k3d-${CLUSTER} -n ai-circus port-forward svc/platform-registry ${PORT}:8000
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
EOF
    systemctl --user daemon-reload
}

case "$ACTION" in
    start)
        stop_background
        if use_service; then
            write_unit  # idempotent — also picks up a changed port or kubectl path
            systemctl --user enable --quiet "$UNIT"
            systemctl --user restart "$UNIT"
            if ! loginctl show-user "$USER" -p Linger 2>/dev/null | grep -q '=yes'; then
                loginctl enable-linger "$USER" 2>/dev/null \
                    || echo "ℹ️  could not enable lingering — the port-forward starts at your first login, not at boot (fix: sudo loginctl enable-linger $USER)"
            fi
            if wait_for_port; then
                echo "✓ platform-registry port-forward on http://localhost:${PORT} — systemd user service ${UNIT} (starts at boot, restarts itself)"
            else
                echo "⏳ ${UNIT} is running and will connect once the cluster answers (journalctl --user -u ${UNIT})"
            fi
        else
            nohup kubectl --context "k3d-${CLUSTER}" -n ai-circus port-forward svc/platform-registry "${PORT}:8000" \
                >"$LOG_FILE" 2>&1 &
            echo $! >"$PID_FILE"
            wait_for_port || true
            echo "✓ platform-registry port-forward on http://localhost:${PORT} (background PID $(cat "$PID_FILE") — no user systemd here: re-run 'make k3s-portforward' after a reboot)"
        fi
        ;;
    stop)
        stop_background
        if [ -f "$UNIT_FILE" ] && use_service; then
            systemctl --user stop "$UNIT"
            echo "✓ platform-registry port-forward stopped (${UNIT} stays enabled — it starts again at the next boot or 'make k3s-portforward')"
        fi
        ;;
    uninstall)
        stop_background
        if [ -f "$UNIT_FILE" ]; then
            systemctl --user disable --now --quiet "$UNIT" 2>/dev/null || true
            rm -f "$UNIT_FILE"
            systemctl --user daemon-reload 2>/dev/null || true
            echo "✓ removed ${UNIT} — 'make k3s-portforward' now needs re-running after each reboot"
        else
            echo "ℹ️  ${UNIT} is not installed"
        fi
        ;;
    status)
        if [ -f "$UNIT_FILE" ] && use_service; then
            systemctl --user --no-pager status "$UNIT" | head -5
        elif [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
            echo "background port-forward running (PID $(cat "$PID_FILE"))"
        else
            echo "no platform-registry port-forward running"
            exit 1
        fi
        ;;
    *)
        echo "❌ unknown action '$ACTION' (start|stop|uninstall|status)" >&2
        exit 1
        ;;
esac
